#!/usr/bin/env bash
# Regenerate supabase/seed.sql from the live local DB, so `npm run db:reset`
# reproduces the real seeded competitions OFFLINE (no provider/API calls).
#
# Refresh flow: re-seed from the provider, then snapshot:
#   npx tsx scripts/seed-competition.ts <slug> --publish
#   npm run db:dump
set -euo pipefail

CID=$(docker ps --filter "name=supabase_db_" --format "{{.Names}}" | head -1)
if [ -z "$CID" ]; then echo "supabase db container not running" >&2; exit 1; fi

OUT="supabase/seed.sql"
# Notes on the flags:
#  --column-inserts  → robust INSERTs (named columns, survive column reordering)
#  NO --disable-triggers → the Supabase seeder isn't superuser, so it can't
#    disable system FK triggers; pg_dump emits FK-ordered rows instead.
#  grep -v '^\\'     → strip psql meta-commands (\restrict/\unrestrict) the
#    Supabase seeder can't parse.
{
  echo "-- ⚠️  GENERATED by scripts/dump-seed.sh — do not hand-edit."
  echo "-- Offline snapshot of seeded competitions"
  echo "-- (competitions/clubs/players/events/player_match_stats)."
  echo "-- Refresh: npx tsx scripts/seed-competition.ts <slug> --publish && npm run db:dump"
  echo ""
  docker exec -i "$CID" pg_dump -U postgres --data-only --column-inserts \
    -t public.competitions -t public.clubs -t public.players -t public.events \
    -t public.player_match_stats \
    | grep -v '^\\'
  # The column-inserts above don't carry computed club strength / player value
  # (they're derived, not snapshotted). Recompute them offline from ratings so
  # db:reset reproduces the transfer economy with no provider/API calls.
  echo ""
  echo "-- Backfill derived club strength + player coin values (see draft.ts)."
  echo "SELECT public.recompute_competition_values(id) FROM public.competitions;"
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines)"
